models/Bills.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "bills".
 *
 * @property int $bill_id
 * @property string|null $bill_no เลขที่ใบเบิก
 * @property int|null $dep_id แผนก/ฝ่ายที่ขอเบิก
 * @property string|null $bill_date วันที่ขอเบิก
 * @property string|null $bill_register ผู้ขอเบิก
 * @property int|null $prepare_id ผู้จ่ายพัสดุ
 * @property int|null $head_id หัวหน้าพัสดุ
 * @property int|null $auth_id ผู้อนุมัติ
 * @property string|null $bill_status_id สถานะใบคำขอ
 *
 * @property Lists[] $lists
 */
class Bills extends \yii\db\ActiveRecord
{

    public $items;

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'bills';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['dep_id', 'prepare_id', 'head_id', 'auth_id'], 'integer'],
            [['bill_date','items'], 'safe'],
            [['bill_status_id'], 'string'],
            [['bill_no', 'bill_register'], 'string', 'max' => 255],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'bill_id' => 'Bill ID',
            'bill_no' => 'เลขที่ใบเบิก',
            'dep_id' => 'แผนก/ฝ่ายที่ขอเบิก',
            'bill_date' => 'วันที่ขอเบิก',
            'bill_register' => 'ผู้ขอเบิก',
            'prepare_id' => 'ผู้จ่ายพัสดุ',
            'head_id' => 'หัวหน้าพัสดุ',
            'auth_id' => 'ผู้อนุมัติ',
            'bill_status_id' => 'สถานะใบคำขอ',
            'items' => 'รายการที่ขอเบิก',
        ];
    }

    /**
     * Gets query for [[Lists]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getLists()
    {
        return $this->hasMany(Lists::className(), ['bill_id' => 'bill_id']);
    }
    
    /**
     * Gets query for [[Status]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getStatus()
    {
        return $this->hasOne(BillStatus::className(), ['bill_status_id' => 'bill_status_id']);
    }
    public function getStatusName()
    {
        return $this->status->status_name;
    }

    /**
     * Gets query for [[Department]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getDepartment()
    {
        return $this->hasOne(Departments::className(), ['dep_id' => 'dep_id']);
    }
    public function getDepName()
    {
        return $this->department->dep_name;
    }

    /**
     * Gets query for [[Officer]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getOfficer()
    {
        return $this->hasOne(Officers::className(), ['officer_id' => 'prepare_id']);
    }
    public function getOfficerName()
    {
        return $this->officer->officer_name;
    }
    public function getOfficerPos()
    {
        return $this->officer->officer_position;
    }

    /**
     * Gets query for [[Header]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getHead()
    {
        return $this->hasOne(Officers::className(), ['officer_id' => 'head_id']);
    }
    public function getHeadName()
    {
        return $this->head->officer_name;
    }
    public function getHeadPos()
    {
        return $this->head->officer_position;
    }
    /**
     * Gets query for [[Authorize]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getAuth()
    {
        return $this->hasOne(Officers::className(), ['officer_id' => 'auth_id']);
    }
    public function getAuthName()
    {
        return $this->auth->officer_name;
    }
    public function getAuthPos()
    {
        return $this->auth->officer_position;
    }

}

controllers/BillsController.php
<?php

namespace app\controllers;

use Yii;
use app\models\bills;
use app\models\BillsSearch;
use app\models\Officers;
use app\models\Office;

use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use kartik\mpdf\Pdf;
use app\models\Lists;
use app\models\ListsSearch;
use yii\base\Exception;


/**
 * BillsController implements the CRUD actions for bills model.
 */
class BillsController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all bills models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new BillsSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $dataProvider->query->orderBy(['bill_id'=>SORT_DESC]);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single bills model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        $searchModel = new ListsSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $dataProvider->query->where(['bill_id' => $id])->all();

        return $this->render('view', [
            'model' => $this->findModel($id),
            //'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Creates a new bills model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        // ส้างใบคำขอเบิก 
        $model = new bills();

        if ($model->load(Yii::$app->request->post())) {
            // สร้าง transection 
            $transaction = Yii::$app->db->beginTransaction();
            // หาค่า bill no ล่าสุด
            $max_bill_no = Bills::find()->select('max(bill_no) as max_no')->scalar();
            // ถ้าหาเลข bill no ไม่พบ ให้ตั้งค่าเป็น 1
            if(!$max_bill_no){
                $max_bill_no = 1;
            }
            try {
                // บันทึกใบคำขอ
                $model->head_id = Officers::find()->select('officer_id')->where(['officer_level'=>'2','active'=>'1'])->limit(1);
                $model->bill_date = date('Y-m-d');
                $model->bill_no = $max_bill_no+1;
                $model->save(false); 
                // ประกาศรับค่าจาก Post
                $items = Yii::$app->request->post();

                //นำรายการขอเบิกที่เลือกมา loop บันทึก
                foreach($items['Bills']['items'] as $key => $val){ 
                    if(empty($val['list_id'])){
                        $lists = new Lists();
                    }else{
                        $lists = Lists::findOne($val['list_id']);
                    }
                    $lists->bill_id = $model->bill_id;
                    $lists->list_item = $val['list_item'];
                    $lists->amount = $val['amount'];   
                    $lists->unit = $val['unit'];                 
                    $lists->comment = $val['comment'];
                    $lists->save();
                }

                $transaction->commit();
                Yii::$app->session->setFlash('success', 'บันทึกข้อมูลเรียบร้อย');
                return $this->redirect(['index']);

            } catch (Exception $e){
                $transaction->rollBack();
                Yii::$app->session->setFlash('error', 'มีข้อผิดพลาดในการบันทึก');
                return $this->redirect(['index']);
            }

            return $this->redirect(['view', 'id' => $model->bill_id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing bills model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $model->items = Lists::find()->where(['bill_id' => $model->bill_id])->all();
        
        if ($model->load(Yii::$app->request->post())) {
            // สร้าง transection 
            $transaction = Yii::$app->db->beginTransaction();

            try {
                // บันทึกใบคำขอ
                $model->save(); 
                // ประกาศรับค่าจาก Post
                $items = Yii::$app->request->post();

                //นำรายการขอเบิกที่เลือกมา loop บันทึก
                foreach($items['Bills']['items'] as $key => $val){ 
                    if(empty($val['list_id'])){
                        $lists = new Lists();
                    }else{
                        $lists = Lists::findOne($val['list_id']);
                    }
                    $lists->bill_id = $model->bill_id;
                    $lists->list_item = $val['list_item'];
                    $lists->amount = $val['amount'];                    
                    $lists->unit = $val['unit'];                 
                    $lists->comment = $val['comment'];
                    $lists->save();
                }

                $transaction->commit();
                Yii::$app->session->setFlash('success', 'บันทึกข้อมูลเรียบร้อย');
                return $this->redirect(['index']);

            } catch (Exception $e){
                $transaction->rollBack();
                Yii::$app->session->setFlash('error', 'มีข้อผิดพลาดในการบันทึก');
                return $this->redirect(['index']);
            }
            return $this->redirect(['view', 'id' => $model->bill_id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing bills model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

        /**
     * Updates an existing bills model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionApprove($id)
    {
        $model = $this->findModel($id);
        $model->items = Lists::find()->where(['bill_id' => $model->bill_id])->all();
        
        $model->auth_id = Yii::$app->user->identity->id;
        $model->bill_status_id = '2';
        $model->save(false);

        return $this->redirect(['index']);
    }

        /**
     * Lists all repairs models.
     * @return mixed
     */
    public function actionPrint($id)
    {
        $model = $this->findModel($id);
        $model->items = Lists::find()->where(['bill_id' => $model->bill_id])->all();        
        $office = Office::find()->one();

        $content = $this->renderPartial('_print', [
            'model' => $model,
            'office' => $office,
        ]);

        $pdf = new Pdf([
            'mode' => Pdf::MODE_UTF8,
            // A4 paper format
            'format' => Pdf::FORMAT_A4,
            // portrait orientation
            'orientation' => Pdf::ORIENT_PORTRAIT,
            // stream to browser inline
            'destination' => Pdf::DEST_BROWSER,
            // your html content input
            'content' => $content,
            // format content from your own css file if needed or use the
            // enhanced bootstrap css built by Krajee for mPDF formatting
            'cssFile' => '@app/web/css/pdf.css',
            // any css to be embedded if required
            'cssInline' => '.bd{border:1.5px solid; text-align: center;} .ar{text-align:right} .imgbd{border:1px solid}',
            // set mPDF properties on the fly
            'options' => ['title' => '.[ใบคำขอเบิกที่ : '.$id],
            // call mPDF methods on the fly
            'methods' => [
                //'SetHeader'=>[''],
                //'SetFooter'=>['{PAGENO}'],
            ]
        ]);

        return $pdf->render();

    }

    /**
     * Finds the bills model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return bills the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = bills::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

controllers/ListsController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Lists;
use app\models\Bills;
use app\models\ListsSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * ListsController implements the CRUD actions for Lists model.
 */
class ListsController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Lists models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new ListsSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Check all Lists models.
     * @return mixed
     */
    public function actionCheck($id)
    {
        $searchModel = new ListsSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $dataProvider->query->where(['bill_id' => $id])->all();

        return $this->render('check', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Lists model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Lists model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Lists();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->list_id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Lists model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $bill = Bills::findone($model->bill_id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            if($bill->bill_status_id == '0'){
                $bill->bill_status_id = '1';
                $bill->prepare_id = Yii::$app->user->identity->id;
                $bill->save(false);    
            }
            return $this->redirect(['view', 'id' => $model->list_id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Lists model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Lists model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Lists the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Lists::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

views/bills/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;
//use unclead\widgets\MultipleInput;
//use unclead\widgets\MultipleInputColumn;
use unclead\multipleinput\MultipleInput;
use kartik\select2\Select2;
use yii\helpers\Url;


use app\models\Departments;
use app\models\Item;

$deps = ArrayHelper::map(Departments::find()->all(), 'dep_id', 'dep_name');
$item = ArrayHelper::map(Item::find()->where(['item_avaliable' => '1'])->all(), 'item_name', 'item_name');
/* @var $this yii\web\View */
/* @var $model app\models\bills */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="bills-form">

    <?php $form = ActiveForm::begin(); ?>

    <?php //= $form->field($model, 'bill_no')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'dep_id')->dropDownList([$deps, ['prompt'=>'เลือกกลุ่มงาน/ฝ่าย/แผนก']]) ?>

    <?php //= $form->field($model, 'bill_date')->textInput() ?>

    <?= $form->field($model, 'bill_register')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'items')->widget(MultipleInput::className(), [
    'max' => 20,
    'columns' => [
        [
            'name'  => 'list_item',
            'headerOptions' => ['style' => 'width:300px'],
            'type'  => Select2::className(),
            'title' => 'รายการ',
            'enableError' => true,
            'options' => [
                'data' => $item,
            ]
        ],
        [
            'name'  => 'amount',
            'type'  => 'textInput',
            'title' => 'จำนวน',
            'defaultValue' => 1,
            'headerOptions' => ['style' => 'width:60px'],
        ],
        [
            'name'  => 'unit',
            'type'  => 'textInput',
            'title' => 'หน่วยนับ',
            'headerOptions' => ['style' => 'width:100px'],
        ],
        [
            'name'  => 'comment',
            'type'  => 'textInput',
            'title' => 'หมายเหตุ',
        ]
    ]
 ]);
?>

    <?php // $form->field($model, 'prepare_id')->textInput() ?>

    <?php // $form->field($model, 'head_id')->textInput() ?>

    <?php // $form->field($model, 'auth_id')->textInput() ?>

    <?php // $form->field($model, 'bill_status_id')->dropDownList([ 5 => '5', 4 => '4', 3 => '3', 2 => '2', 1 => '1', 0 => '0', ], ['prompt' => '']) 
    ?>
<?php $this->registerJs("
    $('#".Html::getInputId($model, 'items')."').on('afterInit', function(){
            //console.log('calls on after initialization event');
        }).on('beforeAddRow', function(e) {
            //console.log('calls on before add row event');
        }).on('afterAddRow', function(e) {
            //console.log('calls on after add row event');
        }).on('beforeDeleteRow', function(e, item){
            //console.log(item);
            return confirm('คุณแน่ใจนะว่าต้องการลบ?'); 
        }).on('afterDeleteRow', function(e, item){
            //console.log(item);
            var id_case = item.find('.list-cell__block_no').find('input[id*=\"".Html::getInputId($model, 'items')."-\"]').val();
            var from_id = item.find('.list-cell__block_no').find('input[id*=\"".Html::getInputId($model, 'items')."-\"][id$=\"-from_id\"]').val();
            var im_id = item.find('.list-cell__block_no').find('input[id*=\"".Html::getInputId($model, 'items')."-\"][id$=\"-id\"]').val();
            //alert(id_case + from_id);
            $.post(\"".Url::to(['/immuno/staining/finance-service-charge-delete'])."\",
                {
                    id_case: id_case,
                    from_id: from_id,
                    im_id: im_id
                },
                function(data, status){
                    //alert(\"Data: \" + data); // + \"Status: \" + status
                }
            );
    });

")?>
    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/bills/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;
use kartik\date\DatePicker;

use app\models\Departments;
$deps = ArrayHelper::map(Departments::find()->all(), 'dep_id', 'dep_name');

/* @var $this yii\web\View */
/* @var $model app\models\BillsSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="bills-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
        'options' => [
            'data-pjax' => 1
        ],
    ]); ?>

    <div class="col-md-2">
    <?= $form->field($model, 'bill_no') ?>
    </div>

    <div class="col-md-4">
    <?= $form->field($model, 'dep_id')->dropDownList([$deps, ['prompt'=>'เลือกกลุ่มงาน/ฝ่าย/แผนก']])  ?>
    </div>

    <div class="col-md-3">
    <?= $form->field($model, 'bill_date')->widget(DatePicker::ClassName(),
    [
        'name' => 'bill_date', 
        'type' => DatePicker::TYPE_COMPONENT_APPEND,
        'options' => ['placeholder' => 'ระบุวันที่ขอเบิก'],
        'pluginOptions' => [
            'format' => 'yyyy-mm-dd',
            'todayHighlight' => true
        ]
    ]); ?>

    </div>

    <div class="col-md-3">
    <?= $form->field($model, 'bill_register') ?>
    </div>

    <?php // echo $form->field($model, 'prepare_id') ?>

    <?php // echo $form->field($model, 'head_id') ?>

    <?php // echo $form->field($model, 'auth_id') ?>

    <?php // echo $form->field($model, 'bill_status_id') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/bills/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\bills */

$this->title = 'Create Bills';
$this->params['breadcrumbs'][] = ['label' => 'Bills', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="bills-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/bills/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
/* @var $this yii\web\View */
/* @var $searchModel app\models\BillsSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'รายการใบคำขอเบิก';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="bills-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?php //= Html::a('เพิ่มใบคำขอเบิก', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?php Pjax::begin(); ?>
    <?php echo $this->render('_search', ['model' => $searchModel]); ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        //'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            //'bill_id',
            'bill_no',
            //'dep_id',
            [
                'attribute'=>'dep_id',
                'label'=>'กลุ่มงาน/ฝ่าย/แผนก',
                'format'=>'text',//raw, html
                'content'=>function($data){
                    return $data->getDepName();
                }
            ],

            'bill_date',
            'bill_register',
            //'prepare_id',
            //'head_id',
            //'auth_id',
            //'bill_status_id',
            [
                'attribute'=>'bill_status_id',
                'label'=>'สถานะรายการ',
                'format'=>'text',//raw, html
                'content'=>function($data){
                    return $data->getStatusName();
                }
            ],

            /*
            [
                'class' => 'yii\grid\ActionColumn',
                'options'=>['style'=>'width:120px;'],
                'buttonOptions'=>['class'=>'btn btn-primary'],
                'template'=>'{approve}',
                'buttons'=>[
                    'approve' => function($url,$model,$key){
                      return Html::a('อนุมัติ',['approve','id'=>$model->bill_id],['class' => 'btn btn-success']);
                    }
                ]
            ],
            */
            [
                'class' => 'yii\grid\ActionColumn',
                'options'=>['style'=>'width:120px;'],
                'buttonOptions'=>['class'=>'btn btn-primary'],
                'template'=>'{view}',
                'buttons'=>[
                    'view' => function($url,$model,$key){
                      return Html::a('รายละเอียด',['view','id'=>$model->bill_id],['class' => 'btn btn-primary']);
                    }
                ]
            ],
            [
                'class' => 'yii\grid\ActionColumn',
                'options'=>['style'=>'width:120px;'],
                'buttonOptions'=>['class'=>'btn btn-warning'],
                'template'=>'{update}',
                'buttons'=>[
                    'update' => function($url,$model,$key){
                      return Yii::$app->user->identity->id == '1' ? (Html::a('ตรวจสอบ',['lists/check','id'=>$model->bill_id],['class' => 'btn btn-warning'])):'';
                    }
                ]
            ],
            [
                'class' => 'yii\grid\ActionColumn',
                'options'=>['style'=>'width:120px;'],
                'buttonOptions'=>['class'=>'btn btn-info'],
                'template'=>'{print}',
                'buttons'=>[
                    'print' => function($url,$model,$key){
                      return Yii::$app->user->identity->id == '1' ? (Html::a('พิมพ์ใบเบิก',['print','id'=>$model->bill_id],['class' => 'btn btn-info'])):'';
                    }
                ]
            ],
        ],
    ]); ?>

    <?php Pjax::end(); ?>

</div>

views/bills/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\bills */

$this->title = 'Update Bills: ' . $model->bill_id;
$this->params['breadcrumbs'][] = ['label' => 'Bills', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->bill_id, 'url' => ['view', 'id' => $model->bill_id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="bills-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/bills/view.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;

/* @var $this yii\web\View */
/* @var $model app\models\bills */

$this->title = $model->bill_id;
$this->params['breadcrumbs'][] = ['label' => 'รายการใบคำขอเบิก', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="bills-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= ($model->bill_status_id == '1' && Yii::$app->user->identity->id =='3') ? (Html::a('อนุมัติเบิกจ่าย', ['approve', 'id' => $model->bill_id], ['class' => 'btn btn-primary'])):''; ?>
        <?=  Html::a('พิมพ์ใบคำขอเบิก', ['print', 'id' => $model->bill_id], ['class' => 'btn btn-info']); ?>
    </p>

    <br>
    <p>
    <div> <b>เลขที่ใบคำขอเบิก </b>: <?= $model->bill_no; ?> </div>  
    <div> <b>กลุ่มงาน/ฝ่าย/แผนกที่ขอเบิก </b>: <?= $model->getDepName(); ?> </div>  
    <div> <b>วันที่ขอเบิก </b>: <?= Yii::$app->formatter->asDate($model->bill_date, 'dd/MM/yyyy'); ?> </div>  
    <div> <b>ผู้ขอเบิก </b>: <?= $model->bill_register; ?> </div>  
    <div> <b>เจ้าหน้าที่ </b>: <?= $model->getOfficerName(); ?> </div>  
    <div> <b>หัวหน้าเจ้าหน้าที่ </b>: <?= $model->getHeadName(); ?> </div>  
    
    <div> <b>สถานะใบคำขอเบิก </b>: <?= $model->getStatusName(); ?> </div> 
    <br>
    </p>
    <?= GridView::widget([
        //'searchModel' => $searchModel,
        'dataProvider' => $dataProvider,
        'columns' => [
            'list_item',
            'amount',
            'cut_off',
            'cut_off_date',
            'remain',
            'comment:ntext',
        ],
    ]) ?>

</div>